### ISSUE TITLE
Clipping for fade-in

### ISSUE THREAD

**Issue by R-Jim** [Manotomo-Alliance-Support-Squad/coco-grad#30]
Using margin for animation cause clipping for fade-in effect when loading heavy image

**Comment by Nephren68** [comment]
Animating the margin property is probably not the best for doing the fade-in slide-up effect, because margin is a CSS property that affects the layout of the page. When it's animated, the browser has to recalculate the layout every frame, which, given the number of cards that are animated on-screen, can affect performance badly. I'd suggest using the transform property instead, which only affects the compositing stage (the compositing stage is pretty fast and is usually hardware-accelerated on the GPU in modern browsers).

With regards to the clipping of the elements, I believe it is caused by `overflow: hidden;` in `.fade-in`.

**Comment by Nephren68** [comment]
It turns out that the clipping is not caused by `overflow: hidden;`. It's most likely due to the card component being inside a container, and that the card goes outside of the bounds of the container, therefore the card gets clipped.
